#!/usr/bin/env bash
# Script that audits DNS
function audit_subdomain {
	local domain="$1"
	local subdomain="$2"

	# list subdomains
	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomain=("subdomain")
	fi

	# configures subdomains
	for sub in "${subdomains[@]}"; do
		record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
		destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
		echo "The subdomain $sub is a $record_type record and points to $destination"
	done
}
