#!/usr/bin/env bash
#Script that transfers a file from a client to a server using scp.

# Check for the correct number of arguments
if [ $# -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE SERVER_IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
private_key_path="$4"

# Use scp to transfer the file to the server's home directory
scp -o StrictHostKeyChecking=no -i "$private_key_path" "$file_path" "$username@$server_ip:~"

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $username@$server_ip:~"
else
    echo "File transfer failed."
fi

