#!/usr/bin/env bash
#Script that configures a new Ubuntu machine
# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple HTML page with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx service
sudo service nginx restart
