#!/usr/bin/env bash
# Script to configure custom HTTP header

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# create html index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirecting to a permanent 301
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Anotibills permanent"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

# Customized HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Restart server service
sudo service nginx restart
