#!/usr/bin/env bash
# Script to configures a new HAproxy as a load balancer

# Installing HAproxy on a lb-01 server
sudo apt-get -y update
sudo pt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

# Copy configuration file into a new file 
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend aiclinic-frontend
        bind *:80
        mode http
        default_backend aiclinic-backend
backend aiclinic-backend
        balance roundrobin
        server 355051-web-01 3.90.70.201:80 check
	server 355051-web-02 100.26.239.192:80 check
' >> /etc/haproxy/haproxy.cfg

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAproxy service
service haproxy restart
