#!/usr/bin/env bash
# Script used to configure nginx on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

