#!/usr/bin/env bash
#Script that displays 'Best School' 10 times, but for the 9th iteration, displays Hi
a=0
while ((a < 10))
do
	echo "Best School"
	((a++))
	if [ $a -eq 9 ]
	then
		echo "Hi"
	fi
done 

