#!/usr/bin/env bash
# Script that loops from 1 to 10
a=0
while ((a < 10))
do
	((a++))
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
