#!/usr/bin/env bash
# Script that displays numbers from 1 to 20
a=1
while ((a < 21))
do
	echo $a
	case "$a" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((a++))
done

